### ISSUE TITLE
Úkol 1 

### ISSUE THREAD

**Issue by verdurcis** [verdurcis/python-for-data-science#1]
Ahoj :).

Dokončila jsem první úkol, tak budu ráda, když se mi na něj podíváš.
Předem díky za jakékoliv opravy a připomínky.

V.

@lutydlitatova

**Comment by lutydlitatova** [comment]
Ahoj Veroniko @verdurcis, vypadá to pěkně 🙂 Nemám nic k opravě, napadlo mne jen, že by se ti hodilo si občas data seřadit, třeba pomocí metody `sort_values`:

* V první části pro zjištění největší přímé závislosti:
```py
df_corr.corr().sort_values('Y', ascending=False)
```

* V druhé části pro zjištění podhodnocené akcie:
```py
df_corr.sort_values("y_difference", ascending=False)
```

Tady je odkaz na dokumentaci `sort_values`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

Napiš, jestli máš ještě nějaký dotaz, jinak můžeme issue uzavřít.
